### ISSUE TITLE
Reduce the number of arguments by packing params into dictionaries

### ISSUE THREAD

**Issue by carterbox** [tomography/tike#15]
We want to reduce the number of parameters for outward facing functions or maybe all functions in general by packing the long lists of parameters into topical dictionaries. For examples:

Parameters `theta`,  `v`, `h` could become `trajectory` by defining
```python
trajectory = {
    'theta' : None,
    'v' : None,
    'h' : None,
}
```
This kind of packing will definitely be employed for the reconstruction parameters of the `tomo.reconstruct` and `pytcho.reconstruct` because those need to be passed through `tike.admm`.

**Comment by dgursoy** [comment]
I'd call it ```scan``` or ```geometry```, etc., because it doesn't need to be a trajectory. For example it can be a mix of random numbers.

**Comment by tekinbicer** [comment]
Is there a reason you pick dictionary over class/struct?

**Comment by carterbox** [comment]
I know that's what you suggest because you suggested it... but you haven't given any reasons **why** using a python class is better for this purpose.

P.S. [python struct](https://docs.python.org/3.6/library/struct.html) is a library for converting python variables into byte strings.

**Comment by tekinbicer** [comment]
I didn't suggest anything in my first message, I asked why you preferred it. 

You have a set of parameters/variables that have logical relationship, i.e. a trajectory/geometry/scan. This is similar to representing a "point" in space: here you don't create a dictionary to represent (x,y), but you create a "point" class.
There are some cases where you might prefer different representations for your data structures, e.g. [see](https://en.wikipedia.org/wiki/AOS_and_SOA) AoS and SoA, but I don't think you are considering these in your current implementation.

**Comment by carterbox** [comment]
I think what you're really asking about it data ordering. Making an array of `C Structs` can be an efficient way to arrange data because a `C Struct` is a contiguous chunk of memory that represents different types, but Python isn't like C, there are no vectorized operations. In Python, classes are actually `dictionaries` with additional overhead because they support adding user defined class functions. XDesign suffers greatly because we can't do vectorized operations on the `Point` class. This is the reason that we're using numpy (to accomplish fast matrix operations). If we want to reorder our data, we can concatenate them into one numpy array and then change the data ordering.

As I mentioned earlier, I don't see a need for class methods, so a Python class is just going to add overhead.

Side note: Here's a reason why this whole idea of reducing input params is bad: It's going to be more difficult to scatter the data across MPI nodes?

**Comment by dgursoy** [comment]
Let’s stick with dicts for now.

**Comment by carterbox** [comment]
Ended up creating dataclasses to handle default parameters for various settings.
