### ISSUE TITLE
Default data types

### ISSUE THREAD

**Issue by carterbox** [tomography/tike#17]
Enforce the use of 32bit data types in order to make the creation plugins and extensions easier. Also, reduce the the complexity of tike.utils; I think there is some redundancy that could be removed.

**Comment by carterbox** [comment]
If all we are ever cast to is 32 bit types, then `tike.utils` only needs something like the following functions:

- 'as_c_bool'
- 'as_c_int',
- 'as_c_int_p',
- 'as_c_float',
- 'as_c_float_p',
- 'as_c_void_p',

**Comment by dgursoy** [comment]
Additionally we may need complex64 types too.

**Comment by carterbox** [comment]
I'm pretty sure that `ctypes` doesn't include a complex type. I'm very sure that the Windows and GNU Complex type specification are not the same. Thus, for compatibility, it's probably better to pass complex arrays as a reshaped float32 array.

**Comment by carterbox** [comment]
Since we are using CuPy, this typing casting problem is not really an issue, we just need to specify the desired type during memory conversion operations from host to device memory.
