### ISSUE TITLE
Use real probes in modeling data for jupyter notebook examples

### ISSUE THREAD

**Issue by nikitinvv** [tomography/tike#56]
Can we use real probes from a ptychography experiment to model data in Jupiter notebook examples? Flat-top gaussian is not a good approximation of real probes. So we cannot correctly test the developed functionality.

**Comment by carterbox** [comment]
I think that would be a good addition as a function in `tike.ptycho.probe`. Do @YudongYao and friends have some scripts in MATLAB that could be converted?

**Comment by YudongYao** [comment]
We have a MATLAB function to generate the probe by propagating from the zone plate, I can share it with you if you need. The easier way is loading a reconstructed experimental probe as the probe in the simulation.

**Comment by carterbox** [comment]
I don't remember when, but the ptychography examples now use real experimental data.
